/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MessageService } from "../message.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MessageCreateInput } from "./MessageCreateInput";
import { Message } from "./Message";
import { MessageFindManyArgs } from "./MessageFindManyArgs";
import { MessageWhereUniqueInput } from "./MessageWhereUniqueInput";
import { MessageUpdateInput } from "./MessageUpdateInput";
import { KeyFragmentFindManyArgs } from "../../keyFragment/base/KeyFragmentFindManyArgs";
import { KeyFragment } from "../../keyFragment/base/KeyFragment";
import { KeyFragmentWhereUniqueInput } from "../../keyFragment/base/KeyFragmentWhereUniqueInput";
import { MessageEncryptionInputDto } from "../MessageEncryptionInputDto";
import { MessageEncryptionOutputDto } from "../MessageEncryptionOutputDto";
import { MessageFragmentationInputDto } from "../MessageFragmentationInputDto";
import { MessageFragmentationOutputDto } from "../MessageFragmentationOutputDto";
import { MessageRetrievalInputDto } from "../MessageRetrievalInputDto";
import { MessageRetrievalOutputDto } from "../MessageRetrievalOutputDto";
import { GovernanceVotingInputDto } from "../GovernanceVotingInputDto";
import { GovernanceVotingOutputDto } from "../GovernanceVotingOutputDto";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MessageControllerBase {
  constructor(
    protected readonly service: MessageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Message })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMessage(
    @common.Body() data: MessageCreateInput
  ): Promise<Message> {
    return await this.service.createMessage({
      data: data,
      select: {
        content: true,
        createdAt: true,
        id: true,
        recipient: true,
        recipientUser: true,
        sender: true,
        senderUser: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Message] })
  @ApiNestedQuery(MessageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async messages(@common.Req() request: Request): Promise<Message[]> {
    const args = plainToClass(MessageFindManyArgs, request.query);
    return this.service.messages({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,
        recipient: true,
        recipientUser: true,
        sender: true,
        senderUser: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Message })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async message(
    @common.Param() params: MessageWhereUniqueInput
  ): Promise<Message | null> {
    const result = await this.service.message({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,
        recipient: true,
        recipientUser: true,
        sender: true,
        senderUser: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Message })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMessage(
    @common.Param() params: MessageWhereUniqueInput,
    @common.Body() data: MessageUpdateInput
  ): Promise<Message | null> {
    try {
      return await this.service.updateMessage({
        where: params,
        data: data,
        select: {
          content: true,
          createdAt: true,
          id: true,
          recipient: true,
          recipientUser: true,
          sender: true,
          senderUser: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Message })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMessage(
    @common.Param() params: MessageWhereUniqueInput
  ): Promise<Message | null> {
    try {
      return await this.service.deleteMessage({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,
          recipient: true,
          recipientUser: true,
          sender: true,
          senderUser: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/keyFragments")
  @ApiNestedQuery(KeyFragmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "KeyFragment",
    action: "read",
    possession: "any",
  })
  async findKeyFragments(
    @common.Req() request: Request,
    @common.Param() params: MessageWhereUniqueInput
  ): Promise<KeyFragment[]> {
    const query = plainToClass(KeyFragmentFindManyArgs, request.query);
    const results = await this.service.findKeyFragments(params.id, {
      ...query,
      select: {
        createdAt: true,
        fragmentData: true,
        id: true,

        message: {
          select: {
            id: true,
          },
        },

        node: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/keyFragments")
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "update",
    possession: "any",
  })
  async connectKeyFragments(
    @common.Param() params: MessageWhereUniqueInput,
    @common.Body() body: KeyFragmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keyFragments: {
        connect: body,
      },
    };
    await this.service.updateMessage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/keyFragments")
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "update",
    possession: "any",
  })
  async updateKeyFragments(
    @common.Param() params: MessageWhereUniqueInput,
    @common.Body() body: KeyFragmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keyFragments: {
        set: body,
      },
    };
    await this.service.updateMessage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/keyFragments")
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "update",
    possession: "any",
  })
  async disconnectKeyFragments(
    @common.Param() params: MessageWhereUniqueInput,
    @common.Body() body: KeyFragmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keyFragments: {
        disconnect: body,
      },
    };
    await this.service.updateMessage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/messages/encrypt")
  @swagger.ApiOkResponse({
    type: MessageEncryptionOutputDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async EncryptMessage(
    @common.Body()
    body: MessageEncryptionInputDto
  ): Promise<MessageEncryptionOutputDto> {
    return this.service.EncryptMessage(body);
  }

  @common.Post("/messages/fragment")
  @swagger.ApiOkResponse({
    type: MessageFragmentationOutputDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async FragmentMessage(
    @common.Body()
    body: MessageFragmentationInputDto
  ): Promise<MessageFragmentationOutputDto> {
    return this.service.FragmentMessage(body);
  }

  @common.Get("/messages/retrieve")
  @swagger.ApiOkResponse({
    type: MessageRetrievalOutputDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async RetrieveMessage(
    @common.Body()
    body: MessageRetrievalInputDto
  ): Promise<MessageRetrievalOutputDto> {
    return this.service.RetrieveMessage(body);
  }

  @common.Post("/voting/submit")
  @swagger.ApiOkResponse({
    type: GovernanceVotingOutputDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async SubmitVote(
    @common.Body()
    body: GovernanceVotingInputDto
  ): Promise<GovernanceVotingOutputDto> {
    return this.service.SubmitVote(body);
  }
}
