/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { NodeService } from "../node.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NodeCreateInput } from "./NodeCreateInput";
import { Node } from "./Node";
import { NodeFindManyArgs } from "./NodeFindManyArgs";
import { NodeWhereUniqueInput } from "./NodeWhereUniqueInput";
import { NodeUpdateInput } from "./NodeUpdateInput";
import { KeyFragmentFindManyArgs } from "../../keyFragment/base/KeyFragmentFindManyArgs";
import { KeyFragment } from "../../keyFragment/base/KeyFragment";
import { KeyFragmentWhereUniqueInput } from "../../keyFragment/base/KeyFragmentWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class NodeControllerBase {
  constructor(
    protected readonly service: NodeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Node })
  @nestAccessControl.UseRoles({
    resource: "Node",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createNode(@common.Body() data: NodeCreateInput): Promise<Node> {
    return await this.service.createNode({
      data: data,
      select: {
        address: true,
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Node] })
  @ApiNestedQuery(NodeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Node",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async nodes(@common.Req() request: Request): Promise<Node[]> {
    const args = plainToClass(NodeFindManyArgs, request.query);
    return this.service.nodes({
      ...args,
      select: {
        address: true,
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Node })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Node",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async node(
    @common.Param() params: NodeWhereUniqueInput
  ): Promise<Node | null> {
    const result = await this.service.node({
      where: params,
      select: {
        address: true,
        createdAt: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Node })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Node",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateNode(
    @common.Param() params: NodeWhereUniqueInput,
    @common.Body() data: NodeUpdateInput
  ): Promise<Node | null> {
    try {
      return await this.service.updateNode({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Node })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Node",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteNode(
    @common.Param() params: NodeWhereUniqueInput
  ): Promise<Node | null> {
    try {
      return await this.service.deleteNode({
        where: params,
        select: {
          address: true,
          createdAt: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/keyFragments")
  @ApiNestedQuery(KeyFragmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "KeyFragment",
    action: "read",
    possession: "any",
  })
  async findKeyFragments(
    @common.Req() request: Request,
    @common.Param() params: NodeWhereUniqueInput
  ): Promise<KeyFragment[]> {
    const query = plainToClass(KeyFragmentFindManyArgs, request.query);
    const results = await this.service.findKeyFragments(params.id, {
      ...query,
      select: {
        createdAt: true,
        fragmentData: true,
        id: true,

        message: {
          select: {
            id: true,
          },
        },

        node: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/keyFragments")
  @nestAccessControl.UseRoles({
    resource: "Node",
    action: "update",
    possession: "any",
  })
  async connectKeyFragments(
    @common.Param() params: NodeWhereUniqueInput,
    @common.Body() body: KeyFragmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keyFragments: {
        connect: body,
      },
    };
    await this.service.updateNode({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/keyFragments")
  @nestAccessControl.UseRoles({
    resource: "Node",
    action: "update",
    possession: "any",
  })
  async updateKeyFragments(
    @common.Param() params: NodeWhereUniqueInput,
    @common.Body() body: KeyFragmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keyFragments: {
        set: body,
      },
    };
    await this.service.updateNode({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/keyFragments")
  @nestAccessControl.UseRoles({
    resource: "Node",
    action: "update",
    possession: "any",
  })
  async disconnectKeyFragments(
    @common.Param() params: NodeWhereUniqueInput,
    @common.Body() body: KeyFragmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      keyFragments: {
        disconnect: body,
      },
    };
    await this.service.updateNode({
      where: params,
      data,
      select: { id: true },
    });
  }
}
