/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { KeyFragmentService } from "../keyFragment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { KeyFragmentCreateInput } from "./KeyFragmentCreateInput";
import { KeyFragment } from "./KeyFragment";
import { KeyFragmentFindManyArgs } from "./KeyFragmentFindManyArgs";
import { KeyFragmentWhereUniqueInput } from "./KeyFragmentWhereUniqueInput";
import { KeyFragmentUpdateInput } from "./KeyFragmentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class KeyFragmentControllerBase {
  constructor(
    protected readonly service: KeyFragmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: KeyFragment })
  @nestAccessControl.UseRoles({
    resource: "KeyFragment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createKeyFragment(
    @common.Body() data: KeyFragmentCreateInput
  ): Promise<KeyFragment> {
    return await this.service.createKeyFragment({
      data: {
        ...data,

        message: data.message
          ? {
              connect: data.message,
            }
          : undefined,

        node: data.node
          ? {
              connect: data.node,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        fragmentData: true,
        id: true,

        message: {
          select: {
            id: true,
          },
        },

        node: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [KeyFragment] })
  @ApiNestedQuery(KeyFragmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "KeyFragment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async keyFragments(@common.Req() request: Request): Promise<KeyFragment[]> {
    const args = plainToClass(KeyFragmentFindManyArgs, request.query);
    return this.service.keyFragments({
      ...args,
      select: {
        createdAt: true,
        fragmentData: true,
        id: true,

        message: {
          select: {
            id: true,
          },
        },

        node: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: KeyFragment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyFragment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async keyFragment(
    @common.Param() params: KeyFragmentWhereUniqueInput
  ): Promise<KeyFragment | null> {
    const result = await this.service.keyFragment({
      where: params,
      select: {
        createdAt: true,
        fragmentData: true,
        id: true,

        message: {
          select: {
            id: true,
          },
        },

        node: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: KeyFragment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyFragment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateKeyFragment(
    @common.Param() params: KeyFragmentWhereUniqueInput,
    @common.Body() data: KeyFragmentUpdateInput
  ): Promise<KeyFragment | null> {
    try {
      return await this.service.updateKeyFragment({
        where: params,
        data: {
          ...data,

          message: data.message
            ? {
                connect: data.message,
              }
            : undefined,

          node: data.node
            ? {
                connect: data.node,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          fragmentData: true,
          id: true,

          message: {
            select: {
              id: true,
            },
          },

          node: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: KeyFragment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyFragment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteKeyFragment(
    @common.Param() params: KeyFragmentWhereUniqueInput
  ): Promise<KeyFragment | null> {
    try {
      return await this.service.deleteKeyFragment({
        where: params,
        select: {
          createdAt: true,
          fragmentData: true,
          id: true,

          message: {
            select: {
              id: true,
            },
          },

          node: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
